### ISSUE TITLE
File Not Found Error for gzip.c, bzip2.c on Gramine Project Server

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/examples#106]
In the GCC examples, two mirrors are specified for downloading bzip2.c and gzip.c. The Gramine Project repository does not contain these files, resulting in a 404 error during download attempts. Additionally, network issues occurring during runtime cause the files to not be downloaded, leading to a hash mismatch from people.csail.mit.edu. 

We cannot do much about network issues but bzip2.c and gzip should be uploaded to Gramine Repository

**Mirrors:**
```
BZIP2_MIRRORS ?= \
	https://people.csail.mit.edu/smcc/projects/single-file-programs/bzip2.c \
	https://packages.gramineproject.io/distfiles/single-file-programs/bzip2.c
BZIP2_HASH ?= 89f331ce93cbf0ee7318802f440f1d7594bb78cf1a82069f2288e0459ec8d729
GZIP_MIRRORS ?= \
	https://people.csail.mit.edu/smcc/projects/single-file-programs/gzip.c \
	https://packages.gramineproject.io/distfiles/single-file-programs/gzip.c
GZIP_HASH ?= 7ec7d87822e6497648580064756f64e47dbd085727910ebbc52a7c240a88dc27
```

**Errors:**
```
download: Trying to fetch https://packages.gramineproject.io/distfiles/single-file-programs/bzip2.c
--2024-09-23 16:47:31--  https://packages.gramineproject.io/distfiles/single-file-programs/bzip2.c
Resolving proxy-dmz.intel.com (proxy-dmz.intel.com)... 
Connecting to proxy-dmz.intel.com (proxy-dmz.intel.com)||:.. connected.
Proxy request sent, awaiting response... 404 Not Found
**2024-09-23 16:47:32 ERROR 404: Not Found.**

download: Trying to fetch https://packages.gramineproject.io/distfiles/single-file-programs/gzip.c
--2024-09-23 16:44:04--  https://packages.gramineproject.io/distfiles/single-file-programs/gzip.c
Resolving proxy-dmz.intel.com (proxy-dmz.intel.com)... 
Connecting to proxy-dmz.intel.com (proxy-dmz.intel.com)||:... connected.
**Proxy request sent, awaiting response... 404 Not Found**
```

**Comment by dimakuv** [comment]
@woju Indeed we don't have the files: https://packages.gramineproject.io/distfiles/

Do you remember if the files were omitted on purpose, or we just forgot to upload them?

**Comment by woju** [comment]
I've uploaded them. I don't recall why they're not there, they were probably missed when we've recreated the toolserver, and we only uploaded files referenced in main repo. Are there any other files missing?

**Comment by dimakuv** [comment]
@anjalirai-intel Could you verify on your end that this issue is resolved now?

**Comment by anjalirai-intel** [comment]
@dimakuv Now, it works. bzip2.c and gzip was downloaded.

@woju We have not done this exercise. We will check all different examples, CI-Examples and get back to you

**Comment by dimakuv** [comment]
This particular issue was resolved.
