### ISSUE TITLE
error: Detected deprecated syntax: 'fs.mount'.

### ISSUE THREAD

**Issue by Lio101** [gramineproject/examples#18]
Hi,
I am trying to use Pytorch example based on [PyTorch PPML Framework Tutorial](https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html), but getting error when trying to use `gramine-direct ./pytorch pytorchexample.py` :

```
~/examples/pytorch$ gramine-direct ./pytorch pytorchexample.py
[P1:T1:] error: Detected deprecated syntax: 'fs.mount'. Consider converting to the new array syntax: 'fs.mounts = [{ type = "chroot", uri = "...", path = "..." }]'.
[P1:shim] error: IPC worker: DkStreamsWaitEvents failed: -11
```

I also tried converting fs.mount to new array syntax in `pytorch.manifest.template`, but then getting different error similar to one given [here](https://github.com/gramineproject/gramine/issues/233) during build process.

**Comment by dimakuv** [comment]
You actually have two independent errors here:
1. The deprecated syntax.
2. The IPC failure.

For the first problem, please show us your `pytorch.manifest.template` -- somewhere there you have duplicated keys (actually, the error tells you on which line of your manifest template this happens, and you can troubleshoot it yourself). This is easy to fix.

For the second problem, it's very much unclear what happens. Can you provide more details? There must be some more log messages to it...

P.S. The PyTorch PPML Framework Tutorial is a bit stale; we haven't updated it in the last 3-4 months. So unfortunately, some steps may be slightly incorrect. We (the Gramine developers) will need to fix this tutorial.

**Comment by Lio101** [comment]
For `pytorch.manifest.template` I am using the same on given [here](https://github.com/gramineproject/examples/blob/master/pytorch/Makefile).

Also I forgot to mention that I am using Azure DC2s V3 VM (Ubuntu 20.04) and followed the steps given [here](https://gramine.readthedocs.io/en/latest/cloud-deployment.html) to setup Gramine.

**Comment by dimakuv** [comment]
Hm. So what is the line where duplicate keys are detected? (This line will be in the `pytorch.manifest.sgx` file, not the template file.)

**Comment by Lio101** [comment]
Sorry, I had made mistake while making changes to `pytorch.manifest.template `  to convert it into new array syntax. Now I am able to build it and perform inferencing in SGX Enclave. 

Thanks for your help!
