### ISSUE TITLE
pytorch example not working

### ISSUE THREAD

**Issue by gagandeep987123** [gramineproject/examples#31]
Hi,
I am trying to run the PyTorch example given in the repo and getting the following error.

```
[P1:T1:] error: Error opening executable /usr/bin/python3.8: -2
[P1:T1:] error: Error during shim_init() in init_important_handles (-2)
```

I am running it in a vmbox on a newly installed ubuntu 20.04 image.
Could you please help?

**Comment by mkow** [comment]
```
~> errno 2
ENOENT 2 No such file or directory
```

I guess that's your problem ;)

**Comment by gagandeep987123** [comment]
I didn't got you.
Do you mean to say that python is not present?
/usr/bin/python3.8 is present in my OS

**Comment by dimakuv** [comment]
@gagandeep987123 Could you provide us with more details?

1. What Gramine version you're using? How did you install/git-clone it?
2. What is the OS distro you're using, and what is the Linux version? (you can show the outputs of `cat /etc/*release*` and `uname -a`.)
3. Did you modify *anything* in the PyTorch example? Maybe you modified the manifest file?
4. Can you show us `ls -la /usr/bin/python3.8`?
5. Can you re-build your PyTorch example with `make SGX=1 DEBUG=1`, so that Gramine will run PyTorch in debug mode? And please show us the resulting Gramine log.

**Comment by gagandeep987123** [comment]
1. I am not sure about the version. But I installed it using the commands given in the home page (sudo apt-get install gramine). Is there a version command that I can run to get the gramine version?
2. 
![Screenshot from 2022-06-13 10-00-52](https://user-images.githubusercontent.com/25634946/173308694-9a3180bb-7cea-48db-90af-36d7236b9ba4.png)
3. No
4. 
![Screenshot from 2022-06-13 10-09-27](https://user-images.githubusercontent.com/25634946/173309018-28f6241e-aa32-467b-8011-6d65869a89f7.png)
5. I am using the non-SGX version as my local machine is not supporting SGX. Following is the output in with debug=1.
![image](https://user-images.githubusercontent.com/25634946/173310397-a6456b2e-76de-4373-9f3f-52e4a4446fe0.png)

**Comment by dimakuv** [comment]
You are using "old" Gramine v1.1. (You can see it from the debug log.)

The manifest syntax was modified between Gramine v1.1 and v1.2. Please install/update Gramine again, and try it with the PyTorch example again.

This is what our [Examples README](https://github.com/gramineproject/examples/blob/master/README.rst) says:

> These examples are tested only against the most recent Gramine release (i.e., these examples are not guaranteed to work with older releases and unreleased versions of Gramine, including the latest master branch commits of Gramine).

So please update to the latest Gramine v1.2. Something like this should suffice:
```
sudo apt-get update
sudo apt-get --only-upgrade install gramine
```

**Comment by gagandeep987123** [comment]
Now I am getting the other error:
`gagan@gagan-VirtualBox:~/examples/pytorch$ gramine-direct ./pytorch ./pytorchexample.py

[::] debug: Gramine was built from commit: 1.2
[::] debug: Host: Linux
[::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[::] debug: Initial VMA region 0x7fffebf33000-0x7fffebfd2000 (LibOS) bookkeeped
[::] debug: Initial VMA region 0x7ffff3fd2000-0x7ffff7fd2000 (pal_init_pool) bookkeeped
[::] debug: Initial VMA region 0x7ffff7fd6000-0x7ffff7fd8000 (vdso) bookkeeped
[::] debug: Initial VMA region 0x7ffff7fd2000-0x7ffff7fd6000 (vvar) bookkeeped
[::] debug: Initial VMA region 0x7fffebfd2000-0x7ffff3fd2000 (pal_internal_me) bookkeeped
[::] debug: ASLR top address adjusted to 0x3bdba37ba000
[::] debug: Shim loaded at 0x7fffebf33000, ready to initialize
[::] debug: mounting "file:." (chroot) under /
[::] debug: mounting "proc" (pseudo) under /proc
[::] debug: mounting "dev" (pseudo) under /dev
[::] debug: mounting "dev:tty" (chroot) under /dev/tty
[::] debug: mounting "sys" (pseudo) under /sys
[::] debug: Creating pipe: pipe.srv:ace303a3e4dfbcb58cd8891eec23d274eef5e011de7aa61bafe4d5938db21c21
[P1:T1:] debug: mounting "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib
[P1:T1:] debug: mounting "file:/lib/x86_64-linux-gnu" (chroot) under /lib/x86_64-linux-gnu
[P1:T1:] debug: mounting "file:/usr" (chroot) under /usr
[P1:T1:] debug: mounting "file:/etc" (chroot) under /etc
[P1:T1:] debug: mounting "file:/tmp" (chroot) under /tmp
[P1:T1:] debug: mounting "file:/usr/lib/python3/dist-packages/" (chroot) under /usr/lib/python3/dist-packages/
[P1:T1:python3.8] debug: Creating pipe: pipe.srv:04822fdde57896d3e8e111beadd63a4aaec082db0975cbe13f23de6bc21cfcf6
[P1:T1:python3.8] debug: Allocating stack at 0 (size = 262144)
[P1:T1:python3.8] debug: loading "file:/usr/bin/python3.8"
[P1:T1:python3.8] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:python3.8] debug: loading "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2"
[P1:T1:python3.8] debug: Creating pipe: pipe.srv:1
[P1:T1:python3.8] debug: Creating pipe: pipe.srv:1626161d01d5bba3b80108d1eba222ffff883835d56d517f207dfe1440afa844
[P1:T1:python3.8] debug: Shim process initialized
[P1:shim] debug: IPC worker started
[P1:T1:python3.8] debug: glibc register library /lib/libc.so.6 loaded at 0x3bdba354f000
[P1:T1:python3.8] debug: glibc register library /lib/libpthread.so.0 loaded at 0x3bdba354a000
[P1:T1:python3.8] debug: glibc register library /lib/libdl.so.2 loaded at 0x3bdba3545000
[P1:T1:python3.8] debug: glibc register library /lib/libutil.so.1 loaded at 0x3bdba3540000
[P1:T1:python3.8] debug: glibc register library /lib/libm.so.6 loaded at 0x3bdba3465000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libexpat.so.1 loaded at 0x3bdba3437000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libz.so.1 loaded at 0x3bdba3419000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3/dist-packages/apt_pkg.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba2ffd000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libapt-pkg.so.6.0 loaded at 0x3bdba2e1e000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libstdc++.so.6 loaded at 0x3bdba2c3c000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libgcc_s.so.1 loaded at 0x3bdba2c21000
[P1:T1:python3.8] debug: glibc register library /lib/libresolv.so.2 loaded at 0x3bdba2c0d000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libbz2.so.1.0 loaded at 0x3bdba2bfa000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/liblzma.so.5 loaded at 0x3bdba2bd1000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/liblz4.so.1 loaded at 0x3bdba2bb0000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libzstd.so.1 loaded at 0x3bdba2b07000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libudev.so.1 loaded at 0x3bdba2ada000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libsystemd.so.0 loaded at 0x3bdba2a2b000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libgcrypt.so.20 loaded at 0x3bdba290d000
[P1:T1:python3.8] debug: glibc register library /lib/librt.so.1 loaded at 0x3bdba2908000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libgpg-error.so.0 loaded at 0x3bdba28e5000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba28dd000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba28d1000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_hashlib.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba28c6000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libcrypto.so.1.1 loaded at 0x3bdba1dcf000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba2737000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libssl.so.1.1 loaded at 0x3bdba1cfc000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba28c0000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba2238000
[P1:T1:python3.8] debug: glibc register library /lib/x86_64-linux-gnu/libmpdec.so.2 loaded at 0x3bdba21ad000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3/dist-packages/simplejson/_speedups.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba28b3000
[P1:T1:python3.8] debug: glibc register library /usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so loaded at 0x3bdba1ba8000
Traceback (most recent call last):
  File "./pytorchexample.py", line 4, in <module>
    from torchvision import models
ModuleNotFoundError: No module named 'torchvision'
[P1:T1:python3.8] debug: ---- shim_exit_group (returning 1)
[P1:T1:python3.8] debug: clearing POSIX locks for pid 1
[P1:T1:python3.8] debug: sync client shutdown: closing handles
[P1:T1:python3.8] debug: sync client shutdown: waiting for confirmation
[P1:T1:python3.8] debug: sync client shutdown: finished
[P1:shim] debug: IPC worker: exiting worker thread
[P1:T1:python3.8] debug: process 1 exited with status 1
`
I believe I need to add the torchvision location. Could you please let me know where should I add that?
I am still following the commands from the pytorch example and I am not using any virtual pip session environment.

**Comment by dimakuv** [comment]
You sure you installed like this: `pip3 install --user torchvision pillow` ?

If yes, try `sudo pip3 install torchvision pillow` instead. I don't remember which one is the correct command. Maybe we have it wrong in our README.

**Comment by gagandeep987123** [comment]
Thanks for the help. It worked with sudo.
