### ISSUE TITLE
tag examples repos for releases

### ISSUE THREAD

**Issue by mythi** [gramineproject/examples#42]
In one of demos I'm using v1.1 Gramine (I know I shouldn't) with examples from this repo. My problem is: how to clone this repo that matches v1.1 functionality.

**Comment by dimakuv** [comment]
Here is the mapping, collected by me with some pointers from @anjalirai-intel (thanks!):

- Gramine v1.3, Examples repo tested on 27. September 2022, commit f2c2d2599c9893a27ab2afc73c19a92dd2ed7661
- Gramine v1.2, Examples repo tested on 25. May 2022, commit a915477df8e74fcae82865b080bcf58d3a8f6637
- Gramine v1.1, Examples repo tested on 3. February 2022, commit 7065d0a45b946d8a85d398eed39b3ec890bac796
- Gramine v1.0, Examples repo *not tested* (? couldn't find historical data), commit adeaf144fc97104b8df845a82a4ef802e5276eab

I agree that we should tag these commits with `v1.0`, `v1.1`, ... -- corresponding to the tags in the core Gramine repo. @mkow Is there anything special we should do with this, or can I just tag the commits?

**Comment by mkow** [comment]
Nah, just tag them, but please be careful as pushing tags goes without review.

**Comment by dimakuv** [comment]
@mythi I just pushed the (lightweight) tags `v1.0`, `v1.1`, ..., with commit mappings as described above.

I'll be grateful if you can verify that these tags work (I mean, at least `v1.1` that you're targeting).

**Comment by mythi** [comment]
> I'll be grateful if you can verify that these tags work (I mean, at least `v1.1` that you're targeting).

I can confirm that with the tag my `Dockerfile` builds OK again:

thanks!

```
diff --git a/demos/cc-gramine-demo/build/Dockerfile b/demos/cc-gramine-demo/build/Dockerfile
index 7e76b09..1b254fc 100644
--- a/demos/cc-gramine-demo/build/Dockerfile
+++ b/demos/cc-gramine-demo/build/Dockerfile
@@ -35,7 +35,7 @@ RUN apt-get update \
     libsgx-quote-ex \
     libsgx-dcap-quote-verify-dev
 
-RUN git clone https://github.com/gramineproject/gramine.git
+RUN git clone -b v1.1 --depth 1 https://github.com/gramineproject/gramine.git
 
 WORKDIR /gramine
 COPY 0001-ra-tls-secret-prov-use-cert-manager-filenames.patch .
@@ -90,7 +90,7 @@ COPY --from=gramine /gramine/meson_build_output /gramine/meson_build_output/
 RUN mkdir /ra-tls-secret-prov
 COPY --from=gramine /gramine/CI-Examples/ra-tls-secret-prov/secret_prov_server_dcap /ra-tls-secret-prov
 
-RUN git clone --depth=1 https://github.com/gramineproject/examples.git
+RUN git clone -b v1.1 --depth=1 https://github.com/gramineproject/examples.git
 WORKDIR /examples/pytorch
 
 ENV PATH="${PATH}:/gramine/meson_build_output/bin"
```
