### ISSUE TITLE
I get "Error during libos_init()" while executing PyTorch with non-SGX Gramine

### ISSUE THREAD

**Issue by arkish** [gramineproject/examples#50]
I get the error [P1:T1:] error: Error during libos_init() in init_exec_handle (-2)
while executing gramine-direct ./pytorch pytorchexample.py after make as per the tutorial. Any suggestions to resolve? Thanks

**Comment by dimakuv** [comment]
@arkish What does `command -v python3` show?

The error means that Gramine cannot find the entrypoint (you can check what entrypoint value is written in `pytorch.manifest` file). The entrypoint should be smth like `/usr/bin/python3`, and this file should obviously exist.

**Comment by arkish** [comment]
`command -v python3` gives me /bin/python3, however the entrypoint written in `pytorch.manifest ` is /bin/python3.6. I changed it to /bin/python3 and still get the same error

**Comment by arkish** [comment]
I set the Dentrypoint to use `command -v python3.10` as per my installation in the `make` file and it works as expected.
