### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision'

### ISSUE THREAD

**Issue by CasellaJr** [gramineproject/examples#58]
When I do `python3 pytorchexample.py` It works. However, when I try to execute with Gramine, both non-SGX and SGX, I have the error in title: "ModuleNotFoundError: No module named 'torchvision'". How can I install torchvision inside Gramine? I have already done "pip3 install --user torchvision pillow".

**Comment by CasellaJr** [comment]
My fault... I did not installed PyTorch under root user, with `sudo -E -H pip3 install ...`

**Comment by dimakuv** [comment]
Ok, let me close the issue then.
