### ISSUE TITLE
I run pytorchexampe.py,but I have encountered some difficulties and need some help.

### ISSUE THREAD

**Issue by Kikyou5473** [gramineproject/examples#60]
root@iZbp1cfgyyg2uznmtvyyjzZ:~/examples/pytorch# gramine-sgx ./pytorch ./pytorchexample.py
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Killed
root@iZbp1cfgyyg2uznmtvyyjzZ:~/examples/pytorch# error: Failed to initialize child process: Broken pipe (PAL_ERROR_CONNFAILED_PIPE)

It did not work properly. Does anyone know why?

**Comment by dimakuv** [comment]
> Killed

This is the culprit. You seem to have too little system memory (RAM + swapfile) to run the PyTorch workload. Assuming you're using our PyTorch example with [4GB per enclave](https://github.com/gramineproject/examples/blob/3be77927bbac64c2a4412f7e49dd5e0a59692b5b/pytorch/pytorch.manifest.template#L33), you'll require 8GB of system memory.

See also https://gramine.readthedocs.io/en/stable/manifest-syntax.html#enclave-size
