### ISSUE TITLE
R  particularly slow

### ISSUE THREAD

**Issue by reclock** [gramineproject/examples#74]
为什么R语言速度特别慢
Why is the speed of R language particularly slow

**Comment by kailun-qin** [comment]
Thanks for the question!

> Why is the speed of R language particularly slow

Could you pls kindly elaborate on what do you mean by "speed" and how "slow" it is (perhaps by sharing your context and stats w/ us)?

I tested [scripts/R-benchmark-25.R](https://github.com/gramineproject/examples/blob/master/r/scripts/R-benchmark-25.R) on my setup w/ both `gramine-sgx` (latest master, specifically commit 4de6aa5) and native, however I didn't see unreasonable perf overhead from the benchmark results.

**Comment by reclock** [comment]
How can I execute the interactive interface of the R command in the sgx environment

**Comment by dimakuv** [comment]
> How can I execute the interactive interface of the R command in the sgx environment

Why would you need to do that? SGX is not intended for interactive sessions.

**Comment by reclock** [comment]
> > How can I execute the interactive interface of the R command in the sgx environment
> 
> Why would you need to do that? SGX is not intended for interactive sessions.


Well, yes, it's just for side use and there's not much demand at the moment

**Comment by reclock** [comment]
R command support, is Rscript command supported? I modified the template file, but Rscript failed to execute the script and there was no result output

**Comment by dimakuv** [comment]
@reclock Please be more specific in your questions.

We haven't played with R for quite some time. We haven't tried any advanced usages (afaik), so maybe Rscript doesn't work indeed in Gramine.

What are the exact commands that fail? How exactly they fail? What is the version of Gramine you're using? What is your manifest file you're using? What do you see in the Gramine trace log?

**Comment by mkow** [comment]
@reclock: please don't use GitHub issues for general support, we use issues to keep track of bugs in Gramine. If you need support then either:
- use GitHub Discussions in the main Gramine repo,
- ask on our Gitter (https://gitter.im/gramineproject/community),
- or send an email to users@gramineproject.io.

Also:
- you didn't provide any technical details about your problems
- each comment you post is about a different issue, unrelated to the others
