### ISSUE TITLE
the nodejs example show error "Invalid application path specified (helloworld.js.manifest does not exist)."

### ISSUE THREAD

**Issue by ShenTD** [gramineproject/examples#85]
I try to run nodejs in gramine and I get the files in the path "https://github.com/gramineproject/examples/tree/master)
/nodejs/", the output are as follows:
1.make check
gramine-direct ./nodejs helloworld.js > OUTPUT
[ Success 1/1 ]

2.gramine-direct helloworld.js 
Invalid application path specified (helloworld.js.manifest does not exist).
The path should point to application configuration files, so that they can be
found after appending corresponding extensions.

**Comment by anjalirai-intel** [comment]
@ShenTD this is the command you need to run `gramine-direct ./nodejs helloworld.js `

**Comment by ShenTD** [comment]
> @ShenTD this is the command you need to run `gramine-direct ./nodejs helloworld.js `

It works. 
by the way, I want use web3.js build a cross-chain server which can run in the gramine. Is this technically feasible?

**Comment by anjalirai-intel** [comment]
@dimakuv @kailun-qin can suggest more on this

**Comment by dimakuv** [comment]
> by the way, I want use web3.js build a cross-chain server which can run in the gramine. Is this technically feasible?

I don't know what web3.js is, so I can't comment. Please just try it out. We'll be happy to learn about the results of your effort!
