### ISSUE TITLE
FetchError: request to https://sepolia.infura.io/v3/ failed, reason: getaddrinfo EAI_AGAIN sepolia.infura.io

### ISSUE THREAD

**Issue by ShenTD** [gramineproject/examples#88]
When I run command
 `node helloworld.js`,it works.
However, encountering an issue when running 'gramine-direct ./nodejs helloworld.js'
I suspect the problem is related to Gramine not allowing JavaScript to connect to external connection.
 How can I enable Node.js code to connect externally via HTTPS in Gramine?

**Comment by dimakuv** [comment]
Have you tried to add this manifest option: `sys.enable_extra_runtime_domain_names_conf = true`. See https://gramine.readthedocs.io/en/stable/manifest-syntax.html

In general, please provide more descriptions of what exactly you're doing, add the Gramine logs, and explain where exactly the application fails.

**Comment by ShenTD** [comment]
> Have you tried to add this manifest option: `sys.enable_extra_runtime_domain_names_conf = true`. See https://gramine.readthedocs.io/en/stable/manifest-syntax.html
> 
> In general, please provide more descriptions of what exactly you're doing, add the Gramine logs, and explain where exactly the application fails.

Thank you for your advice – it worked! Next time I will show more detailed descriptions. Thanks again!
