### ISSUE TITLE
torch.cuda.is_available()

### ISSUE THREAD

**Issue by lei330326** [gramineproject/examples#97]
The result of executing torch.cuda.is_available() on my computer is TRUE but the result of executing it in sgx is False. What is the reason?

/home/hh/miniconda3/envs/gyl/lib/python3.8/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 304: OS call failed or operation not supported on this OS (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False

**Comment by dimakuv** [comment]
What are you trying to achieve? CUDA is a GPU programming platform. Intel SGX and Gramine do **not** support GPUs.
